#!/usr/local/bin/python

import face_recognition
import cv2
import glob
import os.path
import sys
import signal
from sys import stdout as out
import getopt

# This is a demo of running face recognition on live video from your webcam.
# It's a little more complicated than the other example, but it includes some
# basic performance tweaks to make things run a lot faster: 1. Process each
# video frame at 1/4 resolution (though still display it at full resolution) 2.
# Only detect faces in every other frame of video.

# PLEASE NOTE: This example requires OpenCV (the `cv2` library) to be installed
# only to read from your webcam.  OpenCV is *not* required to use the
# face_recognition library. It's only required if you want to run this specific
# demo. If you have trouble installing it, try any of the other demos that
# don't require it instead.

opts, args = getopt.getopt(sys.argv, "v")
show_video = False
for opt, arg in opts:
    if opt == "-v":
        show_video = true

# No, globals aren't the best, but neither is this script!
processing = True
def signal_handler(signal, frame):
    global processing
    processing = False
signal.signal(signal.SIGINT, signal_handler)

# Get a reference to webcam #0 (the default one)
print("Starting Camera... ")
video_capture = cv2.VideoCapture(0)
print("Done.")

print("Loading training data... ")
# Load a sample picture and learn how to recognize it.
source_files = glob.glob("source_images/*.*")
names = []
source_encodings = []
for filename in source_files:
    print(filename)
    image = face_recognition.load_image_file(filename)
    encoding = face_recognition.face_encodings(image)[0]
    names.append(os.path.basename(filename).split(".")[0])
    source_encodings.append(encoding)

print("Done.")
# Initialize some variables
face_locations = []
face_encodings = []
face_names = []
process_this_frame = True

print("Processing video... ")
while processing:
    # Grab a single frame of video
    ret, frame = video_capture.read()

    # Resize frame of video to 1/4 size for faster face recognition processing
    small_frame = cv2.resize(frame, (0, 0), fx=0.25, fy=0.25)

    # Only process every other frame of video to save time
    if process_this_frame:
        # Find all the faces and face encodings in the current frame of video
        face_locations = face_recognition.face_locations(small_frame)
        face_encodings = face_recognition.face_encodings(small_frame, face_locations)

        face_names = []
        for face_encoding in face_encodings:
            matches = face_recognition.compare_faces(source_encodings, face_encoding)
            face_names = face_names + [name for name, match in zip(names, matches) if match]

    process_this_frame = not process_this_frame

    out.write("\r\33[2K")
    out.write(", ".join(sorted(face_names)))
    out.flush()

    if show_video:
        # Display the results
        for (top, right, bottom, left), name in zip(face_locations, face_names):
            # Scale back up face locations since the frame we detected in was scaled to 1/4 size
            top *= 4
            right *= 4
            bottom *= 4
            left *= 4

            # Draw a box around the face
            cv2.rectangle(frame, (left, top), (right, bottom), (0, 0, 255), 2)

            # Draw a label with a name below the face
            # cv2.rectangle(frame, (left, bottom - 35), (right, bottom), (0, 0, 255), cv2.FILLED)
            font = cv2.FONT_HERSHEY_DUPLEX
            cv2.putText(frame, name, (left + 6, bottom - 6), font, 1.0, (255, 255, 255), 1)

        # Display the resulting image
        cv2.imshow('Video', frame)

# Release handle to the webcam
video_capture.release()
cv2.destroyAllWindows()
print("\nDone.")
